POST http://localhost:8088/file/image/delete?objectName=20200414/5678.jpeg

###

POST http://localhost:8088/file/image/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data;name="file";filename="5678.jpeg"

< ./test.jpeg

###

