

POST http://localhost:8088/admin/login
Content-Type: application/json

{

  "username" : "admin",
  "password" : "banyuan"
}

> {% client.global.set("auth_token",response.body.data.token) %}

###

GET http://localhost:8088/role/list?pageNum=1&pageSize=5
Content-Type: application/json
Authorization: Bearer{{auth_token}}

###
###

GET http://localhost:8088/admin/info
Content-Type: application/json
Authorization: Bearer{{auth_token}}

###
POST http://localhost:8088/admin/login
Content-Type: application/json

{

  "username" : "productAdmin",
  "password" : "banyuan"
}

###